version: '3.5'

services:
  postgres:
    image: postgres:14.3
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    restart: always
    networks:
      - app
  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    env_file:
      - ./.env
    ports:
      - "5050:80"
    networks:
      - app

  cache:
    image: redis/redis-stack
    restart: always
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      # map config file(s) from source dir
#      - ./redis-stack/redis-stack.conf:/etc/redis-stack.conf
      - ./redis-stack/redis-stack.conf:/opt/redis-stack/etc/redis-stack.conf
#      - ./redis-stack/redis.conf:/etc/redis/redis.conf
      # map server and client tls certs from tls dir
      - ./tls/server.crt:/etc/ssl/certs/server.crt
      - ./tls/server.key:/etc/ssl/certs/server.key
      - ./tls/root.crt:/etc/ssl/certs/root.crt
      - ./tls/client.crt:/etc/ssl/certs/client.crt
      - ./tls/client.key:/etc/ssl/certs/client.key
      #  map app dir
      - ./app:/home/app
      # create redis-stack's data, log & pid dirs/volumes
      - ./redis-stack/data:/var/lib/redis-stack
      - ./redis-stack/log:/var/log
      - ./redis-stack/pid:/var/run
    networks:
      - app

networks:
  app:
    external: true
volumes:
  cache:
    driver: local